---
- hosts: webserver
  become: yes
  remote_user: lucas
  vars:
    packages:
    - teste1
    - teste2
  tasks:
    - name: Install nginx
      apt: 
        name: nginx
        state: latest
        update_cache: yes
    - name: Enable nginx service
      service:
        name: nginx
        enabled: yes
    - name: Iniciando nginx
      service:
        name: nginx
        state: started
    - name: Copy html
      template:
        src: index.html
        dest: /var/www/html/index.html
    - name: Copy nginx personalizado
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restarted nginx

    - name: teste command
      shell:
        'curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null'
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
    
    - name: add repository
      shell: 
        'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list'

    - name: apt update
      apt:
        name: helm
        state: present
        update_cache: yes
      register: install_helm

    - name: uptime
      command: uptime
      register: output_uptime
    
    - name: debug
      ansible.builtin.debug:
        msg: "{{ output_uptime }}"
    - name: debug
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ packages }}"
  handlers:
  - name: Restarted nginx
    service:
      name: nginx
      state: restarted
